"""DEP-017: data-tool requirements.lock is present."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def test_requirements_lock_exists_and_pins_packages():
    lock = ROOT / "requirements.lock"
    assert lock.is_file()
    text = lock.read_text(encoding="utf-8")
    assert "This file is autogenerated by pip-compile" in text
    assert "flask==2.0.3" in text.lower() or "flask==2.0.3" in text
    assert "flask==" in text.lower()
